packages:
  # Core packages (moved from packages/)
  - 'core/*'
  
  # Remaining packages (UI, API, DB, etc.)
  - 'packages/*'
  
  # Agent system
  - 'agent'
  
  # Operating system components
  - 'os/agent'
  
  # Applications
  - 'apps/*'
  
  # Tooling
  - 'tooling/*'
  
  # Flattened plugins (no @lev-os nesting)
  - 'plugins/*'
  
  # Forge and experimental features
  - 'forge/*'