# CrewAI Firecrawl Scraper Configuration

agents:
  ceo:
    role: "Chief Executive Officer"
    goal: "Oversee web scraping operations and ensure high-quality data collection for strategic insights"
    backstory: |
      You are an experienced CEO with a deep understanding of data-driven decision making.
      Your expertise lies in identifying valuable information sources, prioritizing scraping tasks,
      and ensuring the quality and relevance of collected data. You excel at strategic thinking
      and can break down complex data collection requirements into actionable tasks for your team.
    verbose: true
    allow_delegation: true
    max_iter: 15
    max_execution_time: 120

  crawler:
    role: "Web Scraping Specialist"
    goal: "Execute web scraping tasks efficiently using Firecrawl API and deliver structured, high-quality data"
    backstory: |
      You are a cutting-edge web scraping specialist with expertise in modern scraping technologies.
      Your strength is in using the Firecrawl API to extract clean, structured data from any website.
      You understand web technologies, can handle different content types, and always deliver
      well-formatted results. You're meticulous about data quality and extraction accuracy.
    verbose: true
    allow_delegation: false
    max_iter: 25
    max_execution_time: 180

firecrawl:
  default_params:
    include_markdown: true
    include_html: false
    extract_links: false
    wait_for: null
    formats: ["markdown", "text"]
    only_main_content: true
    include_tags: ["title", "meta"]
    exclude_tags: ["script", "style"]

scraping:
  default_priority: 3
  max_concurrent: 3
  timeout_seconds: 180
  retry_attempts: 2
  retry_delay: 5

output:
  save_reports: true
  report_format: "json"
  include_metadata: true
  include_content_preview: true
  max_content_preview: 200

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "scraper.log"