plugin:
  name: cmd
  version: 1.0.0
  type: core_plugin
  description: Universal command runner and process management

capabilities:
  - process_management
  - git_worktree_operations  
  - job_system_integration
  - constitutional_validation
  - specification_implementation_workflow

commands:
  cmd_exec:
    syntax: "kingly cmd exec <command> [options]"
    description: "Execute command with tracking and cleanup"
    whisper:
      strategies:
        - "Execute commands with proper process isolation"
        - "Track and monitor command execution lifecycle"
        - "Ensure cleanup of resources on completion or failure"
      llm_guidance: "Use process management for safe command execution"
    
  cmd_worktree:
    syntax: "kingly cmd worktree <action> [args]"
    description: "Manage git worktrees for parallel development"
    workflow_context: "./contexts/workflows/spec-to-implementation/context.yaml"
    whisper:
      strategies:
        - "Create isolated git worktrees for parallel development streams"
        - "Apply constitutional AI validation before worktree operations"
        - "Enhanced: Use --spec=<file> --wizard for specification implementation workflow"
      llm_guidance: "Use worktree management for parallel development coordination"
  
  cmd_spec_implement:
    syntax: "kingly cmd spec-implement [--spec=<file>] [--idea=\"<description>\"] [--research=\"<topic>\"] [--phase=<phase>] [--name=<worktree>] [--wizard]"
    description: "Transform specifications into validated development environments through 5-phase workflow"
    handler: "src/commands/spec-implement.js"
    phases:
      - "01-research-requirements: Research and requirement gathering"
      - "02-adr-wizard: Architecture decision record creation"
      - "03-splitting: Complexity assessment and splitting" 
      - "04-bdd-tdd: Test specification generation"
      - "05-environment: Development environment setup"
    whisper:
      entry_points:
        - "Basic idea: --idea=\"AI workflow orchestration\" starts research phase"
        - "Existing spec: --spec=\"_01-prime.md\" validates and enhances"
        - "Research topic: --research=\"JEPA integration\" starts deep research"
        - "Specific phase: --phase=\"adr\" jumps to architectural decisions"
      workflow_guidance:
        - "Phase 1-2 can loop for iterative research and ADR creation"
        - "Phase 3 splitting is gateway - ensures 100% confidence for implementation"
        - "Phase 4-5 generate complete test-driven development environment"
      navigation:
        - "Loose workflow allows back-navigation until splitting commits scope"
        - "Each phase has dedicated system prompt and interaction style"
      llm_guidance: "Use for specification-driven development with phase-specific workflows"
    
  cmd_jobs:
    syntax: "kingly cmd jobs [status|kill|list]"
    description: "Integrate with job system for workflow management"
    whisper:
      strategies:
        - "Connect command execution with workflow orchestration"
        - "Monitor job status and provide lifecycle management"
        - "Enable workflow-aware process coordination"
      llm_guidance: "Use job integration for workflow-coordinated command execution"

reasoning_patterns:
  process_execution:
    prompt: |
      You are managing process execution in a LLM-first system.
      
      Context: User wants to execute commands safely with proper tracking and cleanup.
      
      Your reasoning should:
      1. Assess command safety and resource requirements
      2. Choose appropriate isolation and monitoring strategies
      3. Plan cleanup and error handling approaches
      4. Consider workflow integration opportunities
      
      Always prioritize: Safe execution, proper cleanup, workflow integration.