metadata:
  name: "First Principles Thinking"
  type: "pattern"
  category: "thinking-framework"
  description: "Break down complex problems into fundamental truths and reason up from there"
  author: "Aristotle (ancient origins), popularized by Elon Musk"
  complexity: "high"
  time_estimate: "90-180 minutes"

context:
  role: "First Principles Analyst breaking down complex problems to fundamental truths"
  
  framework_overview: |
    First principles thinking involves breaking down complicated problems into basic elements
    and then reassembling them from the ground up. It's the practice of actively questioning
    every assumption you think you know about a given problem or scenario.

  core_principles:
    - "Question every assumption"
    - "Break down complex problems into fundamental parts"
    - "Rebuild solutions from basic truths"
    - "Avoid reasoning by analogy"
    - "Seek the irreducible truth"

  thinking_process:
    step_1_identify_assumptions:
      description: "List all assumptions about the problem"
      methods:
        - "Ask 'What do I assume to be true?'"
        - "Challenge industry conventions"
        - "Question inherited beliefs"
        - "Identify borrowed conclusions"
      questions:
        - "What assumptions am I making?"
        - "Where did these assumptions come from?"
        - "Are these assumptions necessarily true?"

    step_2_break_down_fundamentals:
      description: "Deconstruct problem to basic elements"
      methods:
        - "Identify core components"
        - "Find irreducible elements"
        - "Separate facts from interpretations"
        - "Locate foundational truths"
      questions:
        - "What are the fundamental truths?"
        - "What cannot be reduced further?"
        - "What is absolutely certain?"

    step_3_rebuild_from_basics:
      description: "Reconstruct understanding from fundamentals"
      methods:
        - "Start with proven facts"
        - "Add verified relationships"
        - "Build logical connections"
        - "Test each step"
      questions:
        - "How do these fundamentals connect?"
        - "What new solutions emerge?"
        - "What possibilities does this reveal?"

  application_domains:
    problem_solving:
      - "Complex technical challenges"
      - "Business model innovation"
      - "Process optimization"
      - "Strategic decision making"
    
    innovation:
      - "Product development"
      - "Technology advancement"
      - "Market creation"
      - "Scientific research"
    
    learning:
      - "Skill acquisition"
      - "Knowledge building"
      - "Understanding systems"
      - "Mastering disciplines"

  common_barriers:
    - barrier: "analogical_thinking"
      description: "Reasoning by analogy instead of fundamentals"
      overcome: "Actively question why things are done certain ways"
    
    - barrier: "accepted_wisdom"
      description: "Accepting conventional wisdom without question"
      overcome: "Challenge every 'best practice' and assumption"
    
    - barrier: "complexity_overwhelm"
      description: "Getting lost in the complexity"
      overcome: "Focus on one fundamental element at a time"
    
    - barrier: "social_pressure"
      description: "Pressure to conform to established thinking"
      overcome: "Value truth over consensus"

  practical_techniques:
    five_whys_deep:
      description: "Ask 'why' repeatedly to reach fundamentals"
      example: "Why is this expensive? → Why do those costs exist? → Why is that process necessary?"
    
    assumption_mapping:
      description: "Create visual map of all assumptions"
      process:
        - "List every assumption"
        - "Categorize as proven/unproven"
        - "Challenge unproven assumptions"
    
    physics_approach:
      description: "Apply scientific method to problems"
      steps:
        - "Define the problem precisely"
        - "Identify fundamental constraints"
        - "Apply known laws/principles"
        - "Test hypothesis rigorously"
    
    cost_breakdown:
      description: "Break costs down to material components"
      example: "Instead of 'batteries are expensive', analyze lithium costs, manufacturing, etc."

  real_world_examples:
    spacex_rockets:
      problem: "Rockets are expensive (~$65M per launch)"
      first_principles: "What are raw material costs? ~$200K in aluminum, carbon fiber, fuel"
      solution: "Reusable rockets, vertical integration, manufacturing innovation"
    
    tesla_batteries:
      problem: "Electric car batteries cost $600/kWh"
      first_principles: "What are material costs? Nickel, cobalt, lithium, etc."
      solution: "Battery chemistry innovation, manufacturing scale, supply chain integration"
    
    southwest_airlines:
      problem: "Air travel is expensive and complicated"
      first_principles: "Transportation from point A to point B"
      solution: "No frills, point-to-point routes, single aircraft type"

  output_structure:
    problem_definition:
      - original_problem: "string"
      - conventional_approach: "how this is typically solved"
      - key_assumptions: "list of assumptions being made"
    
    fundamental_analysis:
      - core_elements: "irreducible components"
      - natural_laws: "physical/economic/logical constraints"
      - proven_facts: "what we know to be absolutely true"
    
    first_principles_solution:
      - reconstructed_approach: "solution built from fundamentals"
      - breakthrough_insights: "new understanding gained"
      - implementation_path: "concrete steps forward"
    
    validation_plan:
      - testable_hypotheses: "what can be tested"
      - success_metrics: "how to measure progress"
      - iteration_plan: "how to refine approach"

  warning_signs:
    - "Because that's how it's always been done"
    - "Industry best practices say..."
    - "Everyone knows that..."
    - "It's impossible because..."
    - "We tried that before and it didn't work"

validation_protocol:
  enable_adversarial_validation: true
  
  step_1_devils_advocate:
    challenges:
      - "Are our 'fundamental truths' actually just unexamined assumptions?"
      - "Could breaking down to first principles miss emergent properties?"
      - "Are we creating false precision by atomizing complex systems?"
      - "Does this approach ignore valuable historical wisdom?"
      - "Are we rebuilding solutions that already exist effectively?"
    
  step_2_devils_advocate_to_devils_advocate:
    meta_validation:
      - "Is skepticism of fundamentals leading to relativism?"
      - "Does dismissing first principles favor status quo bias?"
      - "Are we conflating complexity with depth?"
      - "Is respect for historical wisdom preventing innovation?"
      - "Are existing solutions optimal or just entrenched?"
    
  step_3_refined_analysis:
    integration_points:
      - "Balance fundamental analysis with emergent property awareness"
      - "Validate assumptions through empirical testing where possible"
      - "Acknowledge limits of reductionist approach"
      - "Incorporate valuable historical insights that survive scrutiny"
      - "Test rebuilt solutions against existing alternatives"
    
  step_4_try_again:
    enhanced_methodology:
      - "Apply first principles with complexity science awareness"
      - "Use iterative validation of fundamental assumptions"
      - "Include systems-level verification of reconstructed solutions"
      - "Balance innovation with proven approaches"
      - "Test fundamental insights against multiple validation methods"
    
  step_5_final_synthesis:
    validated_outputs:
      - "Assumptions validated through adversarial testing"
      - "Fundamental truths verified against multiple frameworks"
      - "Solutions tested for both novelty and effectiveness"
      - "Clear delineation between certain and uncertain conclusions"
      - "Risk assessment of first principles approach limitations"

triggers:
  - when: "conventional solutions aren't working"
  - when: "need breakthrough innovation"
  - when: "facing impossible problems"
  - when_semantic: "user stuck on complex problem"
  - when_semantic: "conventional thinking not sufficient"
  - when_semantic: "need fundamental understanding"

integration:
  complements:
    - "systems-thinking"
    - "design-thinking"
    - "scientific-method"
    - "adversarial-validation"
  conflicts_with:
    - "analogical-reasoning"
    - "best-practices-following"
  leads_to:
    - "innovation-frameworks"
    - "problem-solving-methods"
    - "validated-conclusions"